---
ce10 :
  genome_description: nematode
  genome_name: ce10
  chr_names:
    - chrI
    - chrII
    - chrIII
    - chrIV
    - chrV
    - chrM
    - chrX
  seq_dir: hgdownload.cse.ucsc.edu/goldenPath/ce10/chromosomes/
  seq_files:
    - chrI.fa.gz
    - chrII.fa.gz
    - chrIII.fa.gz
    - chrIV.fa.gz
    - chrV.fa.gz
    - chrM.fa.gz
    - chrX.fa.gz
  seq_proc_chr: ~
  gene_track_name: refGene
  gene_track_statement: 'SELECT * FROM ce10.refGene'
  gene_track_annotation_names: 
    - name 
    - name2
  snp_track_name: ~ 
  snp_track_statement: ~
  phastCons_dir: hgdownload.cse.ucsc.edu/goldenPath/ce10/phastCons7way/
  phastCons_files: 
    - ce10.phastCons7way.wigFix.gz
  phastCons_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phastCons_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm $chr'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.soe.ucsc.edu/goldenPath/ce10/phyloP7way/
  phyloP_files: 
    - ce10.phyloP7way.wigFix.gz
  phyloP_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phyloP_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
sacCer3 :
  genome_name: sacCer3
  genome_description: Yeast
  chr_names:
    - chrI
    - chrII
    - chrIII
    - chrIV
    - chrV
    - chrVI
    - chrVII
    - chrVIII
    - chrIX
    - chrX
    - chrXI
    - chrXII
    - chrXIII
    - chrXIV
    - chrXV
    - chrXVI 
    - chrM
  seq_dir: hgdownload.cse.ucsc.edu/goldenPath/sacCer3/chromosomes/
  seq_files:
    - chrI.fa.gz
    - chrII.fa.gz
    - chrIII.fa.gz
    - chrIV.fa.gz
    - chrV.fa.gz
    - chrVI.fa.gz
    - chrVII.fa.gz
    - chrVIII.fa.gz
    - chrIX.fa.gz
    - chrX.fa.gz
    - chrXI.fa.gz
    - chrXII.fa.gz
    - chrXIII.fa.gz
    - chrXIV.fa.gz
    - chrXV.fa.gz
    - chrXVI.fa.gz
    - chrM.fa.gz
  seq_proc_chr: ~
  gene_track_name: xenoRefGene
  gene_track_statement: 'SELECT * FROM sacCer3.xenoRefGene'
  gene_track_annotation_names: 
    - name 
    - name2
  snp_track_name: ~
  snp_track_statement: ~ 
  phastCons_dir: hgdownload.soe.ucsc.edu/goldenPath/sacCer3/phastCons7way/
  phastCons_files:
    - sacCer3.chrI.wigFixed.gz
    - sacCer3.chrII.wigFixed.gz
    - sacCer3.chrII.wigFixed.gz
    - sacCer3.chrIII.wigFixed.gz
    - sacCer3.chrIV.wigFixed.gz
    - sacCer3.chrV.wigFixed.gz
    - sacCer3.chrVI.wigFixed.gz
    - sacCer3.chrVII.wigFixed.gz
    - sacCer3.chrVIII.wigFixed.gz
    - sacCer3.chrIX.wigFixed.gz
    - sacCer3.chrX.wigFixed.gz
    - sacCer3.chrXI.wigFixed.gz
    - sacCer3.chrXII.wigFixed.gz
    - sacCer3.chrXIII.wigFixed.gz
    - sacCer3.chrXIV.wigFixed.gz
    - sacCer3.chrXV.wigFixed.gz
    - sacCer3.chrXVI.wigFixed.gz
    - sacCer3.chrM.wigFixed.gz
  phastCons_proc_init:
    - 'gunzip *.gz'
    - 'for x in  I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI M'
    - 'do mv sacCer3.chr$x.wigFixed chr$x'
    - 'done'
  phastCons_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: ~
  phyloP_files: ~
  phyloP_proc_init: ~
  phyloP_proc_chr: ~
  phyloP_proc_clean_dir: ~
hg38: 
  genome_description: human
  genome_name: hg38
  chr_names:
     - chr1
     - chr2
     - chr3
     - chr4
     - chr5
     - chr6
     - chr7
     - chr8
     - chr9
     - chr10
     - chr11
     - chr12
     - chr13
     - chr14
     - chr15
     - chr16
     - chr17
     - chr18
     - chr19
     - chr20
     - chr21
     - chr22
     - chrM
     - chrX
     - chrY
  seq_dir: hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/
  seq_files:
     - chr1.fa.gz
     - chr2.fa.gz
     - chr3.fa.gz
     - chr4.fa.gz
     - chr5.fa.gz
     - chr6.fa.gz
     - chr7.fa.gz
     - chr8.fa.gz
     - chr9.fa.gz
     - chr10.fa.gz
     - chr11.fa.gz
     - chr12.fa.gz
     - chr13.fa.gz
     - chr14.fa.gz
     - chr15.fa.gz
     - chr16.fa.gz
     - chr17.fa.gz
     - chr18.fa.gz
     - chr19.fa.gz
     - chr20.fa.gz
     - chr21.fa.gz
     - chr22.fa.gz
     - chrM.fa.gz
     - chrX.fa.gz
     - chrY.fa.gz
  seq_proc_chr: ~
  gene_track_name: knownGene
  gene_track_statement: 'SELECT * FROM hg38.knownGene LEFT JOIN hg38.kgXref ON hg38.kgXref.kgID = hg38.knownGene.name'
  gene_track_annotation_names:
    - mRNA 
    - spID
    - spDisplayID
    - geneSymbol
    - refseq
    - protAcc
    - description
    - rfamAcc
  snp_track_name: snp141
  snp_track_statement: 'SELECT $fields FROM hg38.snp141'
  phastCons_dir: hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons7way/
  phastCons_files: 
    - hg38.phastCons7way.wigFix.gz
  phastCons_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phastCons_proc_chr :
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP7way/
  phyloP_files: 
    - hg38.phyloP7way.wigFix.gz
  phyloP_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phyloP_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
hg19: 
  genome_name: hg19
  genome_description: human
  chr_names:
     - chr1
     - chr2
     - chr3
     - chr4
     - chr5
     - chr6
     - chr7
     - chr8
     - chr9
     - chr10
     - chr11
     - chr12
     - chr13
     - chr14
     - chr15
     - chr16
     - chr17
     - chr18
     - chr19
     - chr20
     - chr21
     - chr22
     - chrM
     - chrX
     - chrY
  seq_dir: hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
  seq_files:
     - chr1.fa.gz
     - chr2.fa.gz
     - chr3.fa.gz
     - chr4.fa.gz
     - chr5.fa.gz
     - chr6.fa.gz
     - chr7.fa.gz
     - chr8.fa.gz
     - chr9.fa.gz
     - chr10.fa.gz
     - chr11.fa.gz
     - chr12.fa.gz
     - chr13.fa.gz
     - chr14.fa.gz
     - chr15.fa.gz
     - chr16.fa.gz
     - chr17.fa.gz
     - chr18.fa.gz
     - chr19.fa.gz
     - chr20.fa.gz
     - chr21.fa.gz
     - chr22.fa.gz
     - chrM.fa.gz
     - chrX.fa.gz
     - chrY.fa.gz
  seq_proc_chr: ~
  gene_track_name: knownGene
  gene_track_statement: 'SELECT * FROM hg19.knownGene LEFT JOIN hg19.kgXref ON hg19.kgXref.kgID = hg19.knownGene.name'
  gene_track_annotation_names:
    - mRNA 
    - spID
    - spDisplayID
    - geneSymbol
    - refseq
    - protAcc
    - description
    - rfamAcc
  snp_track_name: snp141
  snp_track_statement: 'SELECT $fields FROM hg19.snp141'
  phastCons_dir: hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
  phastCons_files:
    - chr1.phastCons100way.wigFix.gz
    - chr2.phastCons100way.wigFix.gz
    - chr3.phastCons100way.wigFix.gz
    - chr4.phastCons100way.wigFix.gz
    - chr5.phastCons100way.wigFix.gz
    - chr6.phastCons100way.wigFix.gz
    - chr7.phastCons100way.wigFix.gz
    - chr8.phastCons100way.wigFix.gz
    - chr9.phastCons100way.wigFix.gz
    - chr10.phastCons100way.wigFix.gz
    - chr11.phastCons100way.wigFix.gz
    - chr12.phastCons100way.wigFix.gz
    - chr13.phastCons100way.wigFix.gz
    - chr14.phastCons100way.wigFix.gz
    - chr15.phastCons100way.wigFix.gz
    - chr16.phastCons100way.wigFix.gz
    - chr17.phastCons100way.wigFix.gz
    - chr18.phastCons100way.wigFix.gz
    - chr19.phastCons100way.wigFix.gz
    - chr20.phastCons100way.wigFix.gz
    - chr21.phastCons100way.wigFix.gz
    - chr22.phastCons100way.wigFix.gz
    - chrX.phastCons100way.wigFix.gz
    - chrY.phastCons100way.wigFix.gz
    - chrM.phastCons100way.wigFix.gz
  phastCons_proc_init :
    - 'gunzip *.gz'
    - 'for x in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y M' 
    - 'do mv chr$x.*.wigFix chr$x'
    - 'done'
  phastCons_proc_chr  :
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
  phyloP_files:
    - chr1.phyloP100way.wigFix.gz
    - chr2.phyloP100way.wigFix.gz
    - chr3.phyloP100way.wigFix.gz
    - chr4.phyloP100way.wigFix.gz
    - chr5.phyloP100way.wigFix.gz
    - chr6.phyloP100way.wigFix.gz
    - chr7.phyloP100way.wigFix.gz
    - chr8.phyloP100way.wigFix.gz
    - chr9.phyloP100way.wigFix.gz
    - chr10.phyloP100way.wigFix.gz
    - chr11.phyloP100way.wigFix.gz
    - chr12.phyloP100way.wigFix.gz
    - chr13.phyloP100way.wigFix.gz
    - chr14.phyloP100way.wigFix.gz
    - chr15.phyloP100way.wigFix.gz
    - chr16.phyloP100way.wigFix.gz
    - chr17.phyloP100way.wigFix.gz
    - chr18.phyloP100way.wigFix.gz
    - chr19.phyloP100way.wigFix.gz
    - chr20.phyloP100way.wigFix.gz
    - chr21.phyloP100way.wigFix.gz
    - chr22.phyloP100way.wigFix.gz
    - chrX.phyloP100way.wigFix.gz
    - chrY.phyloP100way.wigFix.gz
    - chrM.phyloP100way.wigFix.gz
  phyloP_proc_init :
    - 'gunzip *.gz'
    - 'for x in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y M' 
    - 'do mv chr$x.*.wigFix chr$x'
    - 'done'
  phyloP_proc_chr  :
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
mm10 : 
  genome_name: mm10
  genome_description: mouse
  chr_names:
     - chr1
     - chr2
     - chr3
     - chr4
     - chr5
     - chr6
     - chr7
     - chr8
     - chr9
     - chr10
     - chr11
     - chr12
     - chr13
     - chr14
     - chr15
     - chr16
     - chr17
     - chr18
     - chr19
     - chrM
     - chrX
     - chrY
  seq_dir: hgdownload.soe.ucsc.edu/goldenPath/mm10/chromosomes/
  seq_files:
     - chr1.fa.gz
     - chr2.fa.gz
     - chr3.fa.gz
     - chr4.fa.gz
     - chr5.fa.gz
     - chr6.fa.gz
     - chr7.fa.gz
     - chr8.fa.gz
     - chr9.fa.gz
     - chr10.fa.gz
     - chr11.fa.gz
     - chr12.fa.gz
     - chr13.fa.gz
     - chr14.fa.gz
     - chr15.fa.gz
     - chr16.fa.gz
     - chr17.fa.gz
     - chr18.fa.gz
     - chr19.fa.gz
     - chrM.fa.gz
     - chrX.fa.gz
     - chrY.fa.gz
  seq_proc_chr: ~
  gene_track_name: knownGene
  gene_track_statement: 'SELECT * FROM mm10.knownGene LEFT JOIN mm10.kgXref ON mm10.kgXref.kgID = mm10.knownGene.name'
  gene_track_annotation_names:
    - mRNA 
    - spID
    - spDisplayID
    - geneSymbol
    - refseq
    - protAcc
    - description
    - rfamAcc
  snp_track_name: snp138
  snp_track_statement:  'SELECT $fields FROM mm10.snp138'
  phastCons_dir: hgdownload.soe.ucsc.edu/goldenPath/mm10/phastCons60way/mm10.60way.phastCons/
  phastCons_files:
    - chr1.phastCons60way.wigFix.gz
    - chr2.phastCons60way.wigFix.gz
    - chr3.phastCons60way.wigFix.gz
    - chr4.phastCons60way.wigFix.gz
    - chr5.phastCons60way.wigFix.gz
    - chr6.phastCons60way.wigFix.gz
    - chr7.phastCons60way.wigFix.gz
    - chr8.phastCons60way.wigFix.gz
    - chr9.phastCons60way.wigFix.gz
    - chr10.phastCons60way.wigFix.gz
    - chr11.phastCons60way.wigFix.gz
    - chr12.phastCons60way.wigFix.gz
    - chr13.phastCons60way.wigFix.gz
    - chr14.phastCons60way.wigFix.gz
    - chr15.phastCons60way.wigFix.gz
    - chr16.phastCons60way.wigFix.gz
    - chr17.phastCons60way.wigFix.gz
    - chr18.phastCons60way.wigFix.gz
    - chr19.phastCons60way.wigFix.gz
    - chrX.phastCons60way.wigFix.gz
    - chrY.phastCons60way.wigFix.gz
    - chrM.phastCons60way.wigFix.gz
  phastCons_proc_init:
    - 'gunzip *.gz'
    - 'for x in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X Y M'
    - 'do mv chr$x.*.wigFix chr$x'
    - 'done'
  phastCons_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.soe.ucsc.edu/goldenPath/mm10/phyloP60way/mm10.60way.phyloP60way/
  phyloP_files:
    - chr1.phyloP60way.wigFix.gz
    - chr2.phyloP60way.wigFix.gz
    - chr3.phyloP60way.wigFix.gz
    - chr4.phyloP60way.wigFix.gz
    - chr5.phyloP60way.wigFix.gz
    - chr6.phyloP60way.wigFix.gz
    - chr7.phyloP60way.wigFix.gz
    - chr8.phyloP60way.wigFix.gz
    - chr9.phyloP60way.wigFix.gz
    - chr10.phyloP60way.wigFix.gz
    - chr11.phyloP60way.wigFix.gz
    - chr12.phyloP60way.wigFix.gz
    - chr13.phyloP60way.wigFix.gz
    - chr14.phyloP60way.wigFix.gz
    - chr15.phyloP60way.wigFix.gz
    - chr16.phyloP60way.wigFix.gz
    - chr17.phyloP60way.wigFix.gz
    - chr18.phyloP60way.wigFix.gz
    - chr19.phyloP60way.wigFix.gz
    - chrX.phyloP60way.wigFix.gz
    - chrY.phyloP60way.wigFix.gz
    - chrM.phyloP60way.wigFix.gz
  phyloP_proc_init :
    - 'gunzip *.gz'
    - 'for x in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X Y M'
    - 'do mv chr$x.*.wigFix chr$x'
    - 'done'
  phyloP_proc_chr  :
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
dm6: 
  genome_description: 'D. melanogaster'
  genome_name: dm6
  chr_names:
    - chr2L
    - chr2R
    - chr3L
    - chr3R
    - chr4
    - chrM
    - chrX
    - chrY
  seq_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/bigZips/
  seq_files: 
     - dm6.fa.gz
  seq_proc_chr:
     - 'extract.py $chr dm6.fa.gz'
     - 'gzip $chr.fa'
     - 'rm *.sh'
  gene_track_name: refGene
  gene_track_statement: 'SELECT * FROM dm6.refGene'
  gene_track_annotation_names: 
    - name 
    - name2
  snp_track_name: ~
  snp_track_statement: ~
  phastCons_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/phastCons27way/
  phastCons_files: 
    - dm6.27way.phastCons.wigFix.gz
  phastCons_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phastCons_proc_chr: 
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
    - 'rm *.sh'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/phyloP27way/
  phyloP_files: 
    - dm6.phyloP27way.wigFix.gz
  phyloP_proc_init: 
    - 'split_wigFix.py *.wigFix.gz'
  phyloP_proc_chr: 
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
danRer7:
  genome_description: Zebrafish
  genome_name: danRer7
  chr_names:
     - chr1
     - chr2
     - chr3
     - chr4
     - chr5
     - chr6
     - chr7
     - chr8
     - chr9
     - chr10
     - chr11
     - chr12
     - chr13
     - chr14
     - chr15
     - chr16
     - chr17
     - chr18
     - chr19
     - chr20
     - chr21
     - chr22    
     - chr23
     - chr24
     - chr25
     - chrM
  seq_dir: hgdownload.cse.ucsc.edu/goldenPath/danRer7/bigZips/
  seq_files:
     - danRer7.fa.gz
  seq_proc_chr:
     - 'extract.py $chr danRer7.fa.gz'
     - 'gzip $chr.fa'
     - 'rm *.sh'
  gene_track_name: refGene
  gene_track_statement: 'SELECT * FROM danRer7.refGene'
  gene_track_annotation_names:
    - name
    - name2
  snp_track_name: ~
  snp_track_statement: ~
  phastCons_dir: hgdownload.cse.ucsc.edu/goldenPath/danRer7/phastCons8way/
  phastCons_files: 
    - vertebrate.phastCons8way.wigFix.gz
  phastCons_proc_init:
    - 'split_wigFix.py *.wigFix.gz'
  phastCons_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
    - 'rm *.sh'
  phastCons_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
  phyloP_dir: hgdownload.cse.ucsc.edu/goldenPath/danRer7/phyloP8way/
  phyloP_files:
    - vertebrate.phyloP8way.wigFix.gz
  phyloP_proc_init:
    - 'split_wigFix.py *.wigFix.gz'
  phyloP_proc_chr:
    - 'create_cons.py $chr $dir'
    - 'cat *.$dir >> $dir.txt'
    - 'rm *.$dir'
    - 'rm $chr'
  phyloP_proc_clean_dir:
    - 'rm chr*'
    - 'rm *.gz'
    - 'gzip *.txt'
    - 'rm *.sh'
