# dm6 with refGene, phyloP, and phastCons
---
genome_name: dm6
genome_description: 'D. melanogaster'
genome_chrs:
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrM
  - chrX
  - chrY
genome_raw_dir: ./dm6/raw
genome_index_dir: ./dm6/index
genome_db_dir: /ssd/twingo/sandbox

sparse_tracks:
  - type: gene
    local_dir: /ssd/twingo/sandbox/dm6/raw/gene
    local_file: refGene.txt.gz
    name: refGene
    sql_statement: 'SELECT * FROM dm6.refGene'
    features:
      - name
      - name2
genome_sized_tracks:
  - name: dm6
    type: genome
    local_dir: /ssd/twingo/sandbox/dm6/raw/seq
    local_files:
      - chr2L.fa.gz
      - chr2R.fa.gz
      - chr3L.fa.gz
      - chr3R.fa.gz
      - chr4.fa.gz
      - chrM.fa.gz
      - chrX.fa.gz
      - chrY.fa.gz
    remote_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/bigZips/
    remote_files:
       - dm6.fa.gz
  - name: phastCons
    type: score
    local_dir: /ssd/twingo/sandbox/dm6/raw/phastCons
    local_files:
      - dm6.27way.phastCons.wigFix.gz
    remote_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/phastCons27way/
    remote_files:
      - dm6.27way.phastCons.wigFix.gz
  - name: phyloP
    type: score
    local_dir: /ssd/twingo/sandbox/dm6/raw/phyloP
    local_files:
      - dm6.phyloP27way.wigFix.gz
    remote_dir: hgdownload.cse.ucsc.edu/goldenPath/dm6/phyloP27way/
    remote_files:
      - dm6.phyloP27way.wigFix.gz
