---
genome_chrs:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chrM
- chrX
- chrY
genome_description: mouse
genome_index_dir: /home/twingo/seqant_dbs/mm10/index
genome_name: mm10
genome_raw_dir: /home/twingo/seqant_dbs/mm10/raw
genome_sized_tracks:
- local_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  name: mm10
  remote_dir: hgdownload.soe.ucsc.edu/goldenPath/mm10/chromosomes/
  remote_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  type: genome
sparse_tracks:
- features:
  - mRNA
  - spID
  - spDisplayID
  - geneSymbol
  - refseq
  - protAcc
  - description
  - rfamAcc
  local_files:
  - mm10.knownGene.chr1.txt
  - mm10.knownGene.chr2.txt
  - mm10.knownGene.chr3.txt
  - mm10.knownGene.chr4.txt
  - mm10.knownGene.chr5.txt
  - mm10.knownGene.chr6.txt
  - mm10.knownGene.chr7.txt
  - mm10.knownGene.chr8.txt
  - mm10.knownGene.chr9.txt
  - mm10.knownGene.chr10.txt
  - mm10.knownGene.chr11.txt
  - mm10.knownGene.chr12.txt
  - mm10.knownGene.chr13.txt
  - mm10.knownGene.chr14.txt
  - mm10.knownGene.chr15.txt
  - mm10.knownGene.chr16.txt
  - mm10.knownGene.chr17.txt
  - mm10.knownGene.chr18.txt
  - mm10.knownGene.chr19.txt
  - mm10.knownGene.chrM.txt
  - mm10.knownGene.chrX.txt
  - mm10.knownGene.chrY.txt
  name: knownGene
  sql_statement: SELECT _gene_fields FROM mm10.knownGene LEFT JOIN mm10.kgXref ON
    mm10.kgXref.kgID = mm10.knownGene.name
  type: gene
- features:
  - name
  - strand
  - refUCSC
  - observed
  - func
  - alleleFreqCount
  - alleles
  - alleleNs
  - alleleFreqs
  local_files:
  - mm10.snp138.chr1.txt
  - mm10.snp138.chr2.txt
  - mm10.snp138.chr3.txt
  - mm10.snp138.chr4.txt
  - mm10.snp138.chr5.txt
  - mm10.snp138.chr6.txt
  - mm10.snp138.chr7.txt
  - mm10.snp138.chr8.txt
  - mm10.snp138.chr9.txt
  - mm10.snp138.chr10.txt
  - mm10.snp138.chr11.txt
  - mm10.snp138.chr12.txt
  - mm10.snp138.chr13.txt
  - mm10.snp138.chr14.txt
  - mm10.snp138.chr15.txt
  - mm10.snp138.chr16.txt
  - mm10.snp138.chr17.txt
  - mm10.snp138.chr18.txt
  - mm10.snp138.chr19.txt
  - mm10.snp138.chrM.txt
  - mm10.snp138.chrX.txt
  - mm10.snp138.chrY.txt
  name: snp138
  sql_statement: SELECT _snp_fields FROM mm10.snp138
  type: snp

