#Our own, special field, tells an interface which fields to run prefix queries on
prefixQueryFields:
    - minorAlleles
    - heterozygotes
    - homozygotes
    - compoundHeterozygotes
    - dbSNP146.alleles
    - clinvar.AlternateAllele
numericalFields:
    - cadd
    - phastCons
    - phyloP
    - Position
    - dbSNP146.alleleNs
    - dbSNP146.alleleFreqs

settings:
    analysis:
        filter:
            synonym_filter:
                type: synonym
                synonyms_path : "analysis/synonyms.txt"
            search_synonym_filter:
                type: synonym
                synonyms_path : "analysis/search-synonyms.txt"
                # synonyms:
                #     - variant,variants => variant,variants,allele,alleles
            type_synonym_filter:
                type: synonym
                synonyms_path : "analysis/type-synonyms.txt"
            exonic_allele_function_synonym_filter:
                type: synonym
                synonyms_path : "analysis/exonic-allele-function-synonyms.txt"
            site_type_synonym_filter:
                type: synonym
                synonyms_path : "analysis/site-type-synonyms.txt"
            codon_map_synonym_filter:
                type: synonym
                synonyms_path : "analysis/codon-map-synonyms.txt"
            autocomplete_filter:
                type: edge_ngram
                min_gram: 1
                max_gram: 20
        
        analyzer:
            autocomplete:
                type: custom
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - synonym_filter
                    - autocomplete_filter
            search_keyword_lowercase:
                type: custom
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - search_synonym_filter
            # keyword_lowercase_synonym_autocomplete:
            #     type: custom
            #     tokenizer: keyword
            #     filter:
            #         - standard
            #         - lowercase
            #         - synonym_filter
            #         - autocomplete_filter
            keyword_lowercase_autocomplete:
                type: custom
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - autocomplete_filter
            search_standard:
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - search_synonym_filter
            search_type_synonym_keyword:
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - type_synonym_filter
            lowercase_keyword:
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
            search_exonic_allele_function_synonym_keyword:
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - exonic_allele_function_synonym_filter
            search_site_type_synonym_keyword:
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - site_type_synonym_filter
            search_codon_synonym_keyword:
                tokenizer: keyword
                filter:
                    - standard
                    - lowercase
                    - codon_map_synonym_filter
mappings:
    _all:
        enabled: false
        # type: string
        # analyzer: autocomplete
        # search_analyzer: search_standard
    properties:
        Fragment:
            type: string
            analyzer: lowercase_keyword
            # chr's are very short, and the "prefix" is a completely valid value
            # so, don't include in all, because many false positivies with ngrams
            include_in_all: false
        Position:
            type: integer
        Type:
            type: string
            analyzer: lowercase_keyword
            search_analyzer: search_type_synonym_keyword
            fields:
                raw:
                    type: string
                    index: not_analyzed
        discordant:
            type: boolean
            include_in_all: false
        heterozygotes:
            type: string
            analyzer: autocomplete
            search_analyzer: search_standard
            fields:
                raw:
                    type: string
                    index: not_analyzed
        homozygotes:
            type: string
            analyzer: autocomplete
            search_analyzer: search_standard
            fields:
                raw:
                    type: string
                    index: not_analyzed
        minorAlleles:
            type: string
            include_in_all: false
            analyzer: lowercase_keyword
        hg19:
            type: string
            include_in_all: false
            analyzer: lowercase_keyword
        refSeq:
            properties:
                siteType:
                    type: string
                    analyzer:  lowercase_keyword
                    search_analyzer: search_site_type_synonym_keyword
                    fields:
                        raw:
                            type: string
                            index: not_analyzed
                exonicAlleleFunction:
                    type: string
                    analyzer:  lowercase_keyword
                    search_analyzer: search_exonic_allele_function_synonym_keyword
                    fields:
                        raw:
                            type: string
                            index: not_analyzed
                referenceCodon:
                    type: string
                    analyzer:  lowercase_keyword
                    search_analyzer: search_codon_synonym_keyword
                alleleCodon:
                    type: string
                    analyzer: lowercase_keyword
                    search_analyzer: search_codon_synonym_keyword
                referenceAminoAcid:
                    type: string
                    analyzer: lowercase_keyword
                    include_in_all: false
                alleleAminoAcid:
                    type: string
                    analyzer:  lowercase_keyword
                    include_in_all: false
                codonPosition:
                    type: short
                    include_in_all: false
                codonNumber:
                    type: integer
                    include_in_all: false
                strand:
                    type: string
                    analyzer: keyword
                    include_in_all: false
                kgID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                mRNA:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                spID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                spDisplayID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                geneSymbol:
                    type: string
                    analyzer:  keyword_lowercase_autocomplete
                    search_analyzer: search_keyword_lowercase
                    fields:
                        raw:
                            type: string
                            index: not_analyzed
                refseq:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                protAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                description:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                rfamAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                nearest:
                    properties:
                        name:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                        geneSymbol:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                clinvar:
                    properties:
                        PhenotypeIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                        OtherIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
        phastCons:
            type: float
            include_in_all: false
        phyloP:
            type: float
            include_in_all: false
        cadd:
            type: float
            include_in_all: false
        dbSNP146:
            properties:
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                strand:
                    type: string
                    analyzer: keyword
                    include_in_all: false
                observed:
                    type: string
                    analyzer: lowercase_keyword
                    include_in_all: false
                class:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                func:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                alleles:
                    type: string
                    analyzer: lowercase_keyword
                    include_in_all: false
                alleleNs:
                    type: integer
                    include_in_all: false
                alleleFreqs:
                    type: float
                    include_in_all: false
        clinvar:
            properties:
                ClinicalSignificance:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                Type:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                Origin:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                ReviewStatus:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                OtherIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                ReferenceAllele:
                    type: string
                    analyzer: lowercase_keyword
                    include_in_all: false
                AlternateAllele:
                    type: string
                    analyzer: lowercase_keyword
                    include_in_all: false
                PhenotypeIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard