settings:
    analysis:
        filter:
            synonym_filter:
                type: synonym
                synonyms_path : "analysis/synonyms.txt"
            search_synonym_filter:
                type: synonym
                synonyms_path : "analysis/search-synonyms.txt"
            type_synonym_filter:
                type: synonym
                synonyms_path : "analysis/type-synonyms.txt"
            indel_expansion_filter:
                type: synonym
                synonyms:
                    - ins,insertion
                    - del,deletion
            autocomplete_filter:
                type: edge_ngram
                min_gram: 1
                max_gram: 20
        
        analyzer:
            autocomplete:
                type: custom
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - synonym_filter
                    - autocomplete_filter
            search_standard:
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - search_synonym_filter
            indel_expansion_standard:
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - indel_expansion_filter
            type_synonym_standard:
                tokenizer: standard
                filter:
                    - standard
                    - lowercase
                    - type_synonym_filter
            # type_autocomplete:
            #     type: custom
            #     tokenizer: standard
            #     filter:
            #         - standard
            #         - lowercase
            #         - type_synonym_filter
            #         - autocomplete_filter
mappings:
    _all:
        type: string
        analyzer: autocomplete
        search_analyzer: search_standard
    properties:
        Fragment:
            type: string
        Position:
            type: integer
        Type:
            type: string
            analyzer: standard
            # Will make _all field respond well to insertion, deletion terms
            search_analyzer: type_synonym_standard
            # Simply too big when doing this; index inflates many fold
            # from this alone
            # analyzer: type_autocomplete
            # search_analyzer: search_standard
        heterozygotes:
            type: string
        homozygotes:
            type: string
        compoundHeterozygotes:
            type: string
        minorAlleles:
            type: string
            include_in_all: false
        hg19:
            type: string
            include_in_all: false
        refSeq:
            properties:
                siteType:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                exonicAlleleFunction:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                referenceCodon:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                alleleAminoAcid:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                codonPosition:
                    type: short
                    include_in_all: false
                codonNumber:
                    type: integer
                    include_in_all: false
                strand:
                    type: string
                    include_in_all: false
                kgID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                mRNA:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                spID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                spDisplayID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                geneSymbol:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                refseq:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                protAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                description:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                rfamAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                nearest:
                    properties:
                        name:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                        geneSymbol:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                clinvar:
                    properties:
                        PhenotypeIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
                        OtherIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: search_standard
        phastCons:
            type: float
            include_in_all: false
        phyloP:
            type: float
            include_in_all: false
        cadd:
            type: float
            include_in_all: false
        dbSNP146:
            properties:
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                strand:
                    type: string
                observed:
                    type: string
                    include_in_all: false
                class:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                func:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                alleles:
                    type: string
                    include_in_all: false
                alleleNs:
                    type: integer
                    include_in_all: false
                alleleFreqs:
                    type: float
                    include_in_all: false
        clinvar:
            properties:
                ClinicalSignificance:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                Type:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                Origin:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                ReviewStatus:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                OtherIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard
                ReferenceAllele:
                    type: string
                    include_in_all: false
                AlternateAllele:
                    type: string
                    include_in_all: false
                PhenotypeIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: search_standard