---
assembly: hg19
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: /ssd/seqant_db_build/hg19_snp142/index_lmdb/
files_dir: /ssd/seqant_db_build/hg19_snp142/raw/
output:
  order:
  - hg19
  - refSeq
  - snp146
  - clinvar
  - cadd
  - phastCons
  - phyloP
statistics:
  gene_track: refSeq
  snp_track: snp146
tracks:
- local_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  name: hg19
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
  remote_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  type: reference
- features:
  - kgID
  - mRNA
  - spID
  - spDisplayID
  - geneSymbol
  - refseq
  - protAcc
  - description
  - rfamAcc
  - name
  local_files:
  - hg19.refGene.chr1.gz
  - hg19.refGene.chr2.gz
  - hg19.refGene.chr3.gz
  - hg19.refGene.chr4.gz
  - hg19.refGene.chr5.gz
  - hg19.refGene.chr6.gz
  - hg19.refGene.chr7.gz
  - hg19.refGene.chr8.gz
  - hg19.refGene.chr9.gz
  - hg19.refGene.chr10.gz
  - hg19.refGene.chr11.gz
  - hg19.refGene.chr12.gz
  - hg19.refGene.chr13.gz
  - hg19.refGene.chr14.gz
  - hg19.refGene.chr15.gz
  - hg19.refGene.chr16.gz
  - hg19.refGene.chr17.gz
  - hg19.refGene.chr18.gz
  - hg19.refGene.chr19.gz
  - hg19.refGene.chr20.gz
  - hg19.refGene.chr21.gz
  - hg19.refGene.chr22.gz
  - hg19.refGene.chrX.gz
  - hg19.refGene.chrY.gz
  name: refSeq
  nearest:
  - name
  - geneSymbol
  join:
    track: clinvar
    features:
      - PhenotypeIDs
      - OtherIDs
  sql_statement: SELECT * FROM hg19.refGene LEFT JOIN hg19.kgXref ON hg19.kgXref.refseq = hg19.refGene.name
  type: gene
- local_files:
  - chr1.phastCons100way.wigFix.gz
  - chr2.phastCons100way.wigFix.gz
  - chr3.phastCons100way.wigFix.gz
  - chr4.phastCons100way.wigFix.gz
  - chr5.phastCons100way.wigFix.gz
  - chr6.phastCons100way.wigFix.gz
  - chr7.phastCons100way.wigFix.gz
  - chr8.phastCons100way.wigFix.gz
  - chr9.phastCons100way.wigFix.gz
  - chr10.phastCons100way.wigFix.gz
  - chr11.phastCons100way.wigFix.gz
  - chr12.phastCons100way.wigFix.gz
  - chr13.phastCons100way.wigFix.gz
  - chr14.phastCons100way.wigFix.gz
  - chr15.phastCons100way.wigFix.gz
  - chr16.phastCons100way.wigFix.gz
  - chr17.phastCons100way.wigFix.gz
  - chr18.phastCons100way.wigFix.gz
  - chr19.phastCons100way.wigFix.gz
  - chr20.phastCons100way.wigFix.gz
  - chr21.phastCons100way.wigFix.gz
  - chr22.phastCons100way.wigFix.gz
  - chrX.phastCons100way.wigFix.gz
  - chrY.phastCons100way.wigFix.gz
  - chrM.phastCons100way.wigFix.gz
  name: phastCons
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
  remote_files:
  - chr1.phastCons100way.wigFix.gz
  - chr2.phastCons100way.wigFix.gz
  - chr3.phastCons100way.wigFix.gz
  - chr4.phastCons100way.wigFix.gz
  - chr5.phastCons100way.wigFix.gz
  - chr6.phastCons100way.wigFix.gz
  - chr7.phastCons100way.wigFix.gz
  - chr8.phastCons100way.wigFix.gz
  - chr9.phastCons100way.wigFix.gz
  - chr10.phastCons100way.wigFix.gz
  - chr11.phastCons100way.wigFix.gz
  - chr12.phastCons100way.wigFix.gz
  - chr13.phastCons100way.wigFix.gz
  - chr14.phastCons100way.wigFix.gz
  - chr15.phastCons100way.wigFix.gz
  - chr16.phastCons100way.wigFix.gz
  - chr17.phastCons100way.wigFix.gz
  - chr18.phastCons100way.wigFix.gz
  - chr19.phastCons100way.wigFix.gz
  - chr20.phastCons100way.wigFix.gz
  - chr21.phastCons100way.wigFix.gz
  - chr22.phastCons100way.wigFix.gz
  - chrX.phastCons100way.wigFix.gz
  - chrY.phastCons100way.wigFix.gz
  - chrM.phastCons100way.wigFix.gz
  type: score
- local_files:
  - chr1.phyloP100way.wigFix.gz
  - chr2.phyloP100way.wigFix.gz
  - chr3.phyloP100way.wigFix.gz
  - chr4.phyloP100way.wigFix.gz
  - chr5.phyloP100way.wigFix.gz
  - chr6.phyloP100way.wigFix.gz
  - chr7.phyloP100way.wigFix.gz
  - chr8.phyloP100way.wigFix.gz
  - chr9.phyloP100way.wigFix.gz
  - chr10.phyloP100way.wigFix.gz
  - chr11.phyloP100way.wigFix.gz
  - chr12.phyloP100way.wigFix.gz
  - chr13.phyloP100way.wigFix.gz
  - chr14.phyloP100way.wigFix.gz
  - chr15.phyloP100way.wigFix.gz
  - chr16.phyloP100way.wigFix.gz
  - chr17.phyloP100way.wigFix.gz
  - chr18.phyloP100way.wigFix.gz
  - chr19.phyloP100way.wigFix.gz
  - chr20.phyloP100way.wigFix.gz
  - chr21.phyloP100way.wigFix.gz
  - chr22.phyloP100way.wigFix.gz
  - chrX.phyloP100way.wigFix.gz
  - chrY.phyloP100way.wigFix.gz
  - chrM.phyloP100way.wigFix.gz
  name: phyloP
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
  remote_files:
  - chr1.phyloP100way.wigFix.gz
  - chr2.phyloP100way.wigFix.gz
  - chr3.phyloP100way.wigFix.gz
  - chr4.phyloP100way.wigFix.gz
  - chr5.phyloP100way.wigFix.gz
  - chr6.phyloP100way.wigFix.gz
  - chr7.phyloP100way.wigFix.gz
  - chr8.phyloP100way.wigFix.gz
  - chr9.phyloP100way.wigFix.gz
  - chr10.phyloP100way.wigFix.gz
  - chr11.phyloP100way.wigFix.gz
  - chr12.phyloP100way.wigFix.gz
  - chr13.phyloP100way.wigFix.gz
  - chr14.phyloP100way.wigFix.gz
  - chr15.phyloP100way.wigFix.gz
  - chr16.phyloP100way.wigFix.gz
  - chr17.phyloP100way.wigFix.gz
  - chr18.phyloP100way.wigFix.gz
  - chr19.phyloP100way.wigFix.gz
  - chr20.phyloP100way.wigFix.gz
  - chr21.phyloP100way.wigFix.gz
  - chr22.phyloP100way.wigFix.gz
  - chrX.phyloP100way.wigFix.gz
  - chrY.phyloP100way.wigFix.gz
  - chrM.phyloP100way.wigFix.gz
  type: score
- local_files:
  - whole_genome_SNVs.tsv.gz
  name: cadd
  type: cadd
- features:
  - name
  - strand
  - observed
  - class
  - func
  - alleles
  - alleleNs: int
  - alleleFreqs: float
  local_files:
  - hg19.snp146.chr1.gz
  - hg19.snp146.chr2.gz
  - hg19.snp146.chr3.gz
  - hg19.snp146.chr4.gz
  - hg19.snp146.chr5.gz
  - hg19.snp146.chr6.gz
  - hg19.snp146.chr7.gz
  - hg19.snp146.chr8.gz
  - hg19.snp146.chr9.gz
  - hg19.snp146.chr10.gz
  - hg19.snp146.chr11.gz
  - hg19.snp146.chr12.gz
  - hg19.snp146.chr13.gz
  - hg19.snp146.chr14.gz
  - hg19.snp146.chr15.gz
  - hg19.snp146.chr16.gz
  - hg19.snp146.chr17.gz
  - hg19.snp146.chr18.gz
  - hg19.snp146.chr19.gz
  - hg19.snp146.chr20.gz
  - hg19.snp146.chr21.gz
  - hg19.snp146.chr22.gz
  - hg19.snp146.chrM.gz
  - hg19.snp146.chrX.gz
  - hg19.snp146.chrY.gz
  name: snp146
  sql_statement: SELECT * FROM hg19.snp146
  type: sparse
- build_field_transformations:
    Chromosome: chr .
  build_row_filters:
    Assembly: == GRCh37
  features:
  - ClinicalSignificance
  - Type
  - Origin
  - ReviewStatus
  - OtherIDs
  - ReferenceAllele
  - AlternateAllele
  - PhenotypeIDs
  local_files:
  - variant_summary.txt
  name: clinvar
  based: 1
  remote_dir: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/
  remote_files:
  - variant_summary.txt.gz
  required_fields_map:
  - Chromosome: chrom
  - Start: chromStart
  - Stop: chromEnd
  type: sparse

