---
genome_chrs:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
genome_description: human
genome_name: hg19 
database_dir: /ssd/seqant_db_build/hg19_snp142/index_lmdb/
files_dir: /ssd/seqant_db_build/hg19_snp142/raw/
tracks:
- name:
    reference: r
  type: ref
  local_files:
    - chr1.fa.gz
    - chr2.fa.gz
    - chr3.fa.gz
    - chr4.fa.gz
    - chr5.fa.gz
    - chr6.fa.gz
    - chr7.fa.gz
    - chr8.fa.gz
    - chr9.fa.gz
    - chr10.fa.gz
    - chr11.fa.gz
    - chr12.fa.gz
    - chr13.fa.gz
    - chr14.fa.gz
    - chr15.fa.gz
    - chr16.fa.gz
    - chr17.fa.gz
    - chr18.fa.gz
    - chr19.fa.gz
    - chr20.fa.gz
    - chr21.fa.gz
    - chr22.fa.gz
    - chrM.fa.gz
    - chrX.fa.gz
    - chrY.fa.gz
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
  remote_files:
    - chr1.fa.gz
    - chr2.fa.gz
    - chr3.fa.gz
    - chr4.fa.gz
    - chr5.fa.gz
    - chr6.fa.gz
    - chr7.fa.gz
    - chr8.fa.gz
    - chr9.fa.gz
    - chr10.fa.gz
    - chr11.fa.gz
    - chr12.fa.gz
    - chr13.fa.gz
    - chr14.fa.gz
    - chr15.fa.gz
    - chr16.fa.gz
    - chr17.fa.gz
    - chr18.fa.gz
    - chr19.fa.gz
    - chr20.fa.gz
    - chr21.fa.gz
    - chr22.fa.gz
    - chrM.fa.gz
    - chrX.fa.gz
    - chrY.fa.gz
- name:
    phastCons: C
  type: score
  local_files:
    - chr1.phastCons100way.wigFix.gz
    - chr2.phastCons100way.wigFix.gz
    - chr3.phastCons100way.wigFix.gz
    - chr4.phastCons100way.wigFix.gz
    - chr5.phastCons100way.wigFix.gz
    - chr6.phastCons100way.wigFix.gz
    - chr7.phastCons100way.wigFix.gz
    - chr8.phastCons100way.wigFix.gz
    - chr9.phastCons100way.wigFix.gz
    - chr10.phastCons100way.wigFix.gz
    - chr11.phastCons100way.wigFix.gz
    - chr12.phastCons100way.wigFix.gz
    - chr13.phastCons100way.wigFix.gz
    - chr14.phastCons100way.wigFix.gz
    - chr15.phastCons100way.wigFix.gz
    - chr16.phastCons100way.wigFix.gz
    - chr17.phastCons100way.wigFix.gz
    - chr18.phastCons100way.wigFix.gz
    - chr19.phastCons100way.wigFix.gz
    - chr20.phastCons100way.wigFix.gz
    - chr21.phastCons100way.wigFix.gz
    - chr22.phastCons100way.wigFix.gz
    - chrX.phastCons100way.wigFix.gz
    - chrY.phastCons100way.wigFix.gz
    - chrM.phastCons100way.wigFix.gz
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
  remote_files:
    - chr1.phastCons100way.wigFix.gz
    - chr2.phastCons100way.wigFix.gz
    - chr3.phastCons100way.wigFix.gz
    - chr4.phastCons100way.wigFix.gz
    - chr5.phastCons100way.wigFix.gz
    - chr6.phastCons100way.wigFix.gz
    - chr7.phastCons100way.wigFix.gz
    - chr8.phastCons100way.wigFix.gz
    - chr9.phastCons100way.wigFix.gz
    - chr10.phastCons100way.wigFix.gz
    - chr11.phastCons100way.wigFix.gz
    - chr12.phastCons100way.wigFix.gz
    - chr13.phastCons100way.wigFix.gz
    - chr14.phastCons100way.wigFix.gz
    - chr15.phastCons100way.wigFix.gz
    - chr16.phastCons100way.wigFix.gz
    - chr17.phastCons100way.wigFix.gz
    - chr18.phastCons100way.wigFix.gz
    - chr19.phastCons100way.wigFix.gz
    - chr20.phastCons100way.wigFix.gz
    - chr21.phastCons100way.wigFix.gz
    - chr22.phastCons100way.wigFix.gz
    - chrX.phastCons100way.wigFix.gz
    - chrY.phastCons100way.wigFix.gz
    - chrM.phastCons100way.wigFix.gz
- name:
    phyloP: P
  type: score
  local_files:
    - chr1.phyloP100way.wigFix.gz
    - chr2.phyloP100way.wigFix.gz
    - chr3.phyloP100way.wigFix.gz
    - chr4.phyloP100way.wigFix.gz
    - chr5.phyloP100way.wigFix.gz
    - chr6.phyloP100way.wigFix.gz
    - chr7.phyloP100way.wigFix.gz
    - chr8.phyloP100way.wigFix.gz
    - chr9.phyloP100way.wigFix.gz
    - chr10.phyloP100way.wigFix.gz
    - chr11.phyloP100way.wigFix.gz
    - chr12.phyloP100way.wigFix.gz
    - chr13.phyloP100way.wigFix.gz
    - chr14.phyloP100way.wigFix.gz
    - chr15.phyloP100way.wigFix.gz
    - chr16.phyloP100way.wigFix.gz
    - chr17.phyloP100way.wigFix.gz
    - chr18.phyloP100way.wigFix.gz
    - chr19.phyloP100way.wigFix.gz
    - chr20.phyloP100way.wigFix.gz
    - chr21.phyloP100way.wigFix.gz
    - chr22.phyloP100way.wigFix.gz
    - chrX.phyloP100way.wigFix.gz
    - chrY.phyloP100way.wigFix.gz
    - chrM.phyloP100way.wigFix.gz
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
  remote_files:
    - chr1.phyloP100way.wigFix.gz
    - chr2.phyloP100way.wigFix.gz
    - chr3.phyloP100way.wigFix.gz
    - chr4.phyloP100way.wigFix.gz
    - chr5.phyloP100way.wigFix.gz
    - chr6.phyloP100way.wigFix.gz
    - chr7.phyloP100way.wigFix.gz
    - chr8.phyloP100way.wigFix.gz
    - chr9.phyloP100way.wigFix.gz
    - chr10.phyloP100way.wigFix.gz
    - chr11.phyloP100way.wigFix.gz
    - chr12.phyloP100way.wigFix.gz
    - chr13.phyloP100way.wigFix.gz
    - chr14.phyloP100way.wigFix.gz
    - chr15.phyloP100way.wigFix.gz
    - chr16.phyloP100way.wigFix.gz
    - chr17.phyloP100way.wigFix.gz
    - chr18.phyloP100way.wigFix.gz
    - chr19.phyloP100way.wigFix.gz
    - chr20.phyloP100way.wigFix.gz
    - chr21.phyloP100way.wigFix.gz
    - chr22.phyloP100way.wigFix.gz
    - chrX.phyloP100way.wigFix.gz
    - chrY.phyloP100way.wigFix.gz
    - chrM.phyloP100way.wigFix.gz
- name:
    gene: r
  type: gene
  features:
    - kgID
    - mRNA
    - spID
    - spDisplayID
    - geneSymbol
    - refseq
    - protAcc
    - description
    - rfamAcc
  local_files:
    - hg19.refGene.chr1.txt
  sql_statement: SELECT _gene_fields FROM hg19.refGene LEFT JOIN hg19.kgXref ON hg19.kgXref.refseq
    = hg19.refGene.name
- name:
    snp: s
  type: sparse
  features:
    - name:
        store: n
    - strand:
        store: s
    - refUCSC:
        store: r
    - observed:
        store: o
    - func:
        store: f
    - alleleFreqCount:
        store: q
    - alleles:
        store: a
    - alleleNs:
        type: int
        store: N
    - alleleFreqs:
        store: Q
  local_files:
    - hg19.snp142.chr1.txt
    - hg19.snp142.chr2.txt
    - hg19.snp142.chr3.txt
    - hg19.snp142.chr4.txt
    - hg19.snp142.chr5.txt
    - hg19.snp142.chr6.txt
    - hg19.snp142.chr7.txt
    - hg19.snp142.chr8.txt
    - hg19.snp142.chr9.txt
    - hg19.snp142.chr10.txt
    - hg19.snp142.chr11.txt
    - hg19.snp142.chr12.txt
    - hg19.snp142.chr13.txt
    - hg19.snp142.chr14.txt
    - hg19.snp142.chr15.txt
    - hg19.snp142.chr16.txt
    - hg19.snp142.chr17.txt
    - hg19.snp142.chr18.txt
    - hg19.snp142.chr19.txt
    - hg19.snp142.chr20.txt
    - hg19.snp142.chr21.txt
    - hg19.snp142.chr22.txt
    - hg19.snp142.chrM.txt
    - hg19.snp142.chrX.txt
    - hg19.snp142.chrY.txt
  sql_statement: SELECT _snp_fields FROM hg19.snp142
# - name: cadd
#   type: score
#   local_files:
#     - hg19.cadd.fixed.gz
#   remote_dir: NA
#   remote_files:
#   - NA