settings:
    analysis:
        filter: 
            autocomplete_filter:
                type: edge_ngram
                min_gram: 2
                max_gram: 20
            
        
        analyzer:
            autocomplete:
                type: custom
                tokenizer: standard
                filter:
                    - lowercase
                    - autocomplete_filter
mappings:
    Fragment:
        type: string
    Position:
        type: integer
    Type:
        type: string
    heterozygotes:
        type: string
        analyzer:  autocomplete
        search_analyzer: standard
    homozygotes:
        type: string
        analyzer:  autocomplete
        search_analyzer: standard
    compoundHeterozygotes:
        type: string
        analyzer:  autocomplete
        search_analyzer: standard
    minorAlleles:
        type: string
        analyzer:  autocomplete
        search_analyzer: standard
    hg38:
        type: string
    refSeq:
        properties:
            siteType:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            exonicAlleleFunction:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            referenceCodon:
                type: string
            alleleAminoAcid:
                type: string
            codonPosition:
                type: short
            codonNumber:
                type: integer
            strand:
                type: string
            kgID:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            mRNA:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            spID:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            spDisplayID:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            geneSymbol:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            refseq:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            protAcc:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            description:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            rfamAcc:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            name:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            nearest:
                properties:
                    name:
                        type: string
                        analyzer:  autocomplete
                        search_analyzer: standard
                    geneSymbol:
                        type: string
                        analyzer:  autocomplete
                        search_analyzer: standard
                    PhenotypeIDs:
                        type: string
                        analyzer:  autocomplete
                        search_analyzer: standard
                    OtherIDs:
                        type: string
                        analyzer:  autocomplete
                        search_analyzer: standard
    phastCons:
        type: float
    phyloP:
        type: float
    cadd:
        type: float
    dbSNP146:
        properties:
            name:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            strand:
                type: string
            observed:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            class:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            func:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            alleles:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            alleleNs:
                type: integer
            alleleFreqs:
                type: float
    clinvar:
        properties:
            ClinicalSignificance:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            Type:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            Origin:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            ReviewStatus:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            OtherIDs:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            ReferenceAllele:
                type: string
            AlternateAllele:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard
            PhenotypeIDs:
                type: string
                analyzer:  autocomplete
                search_analyzer: standard