---
assembly: hg38
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: ~
files_dir: ~
statistics:
  refTrackField: ref
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  siteTypeField: refSeq.siteType
temp_dir: ~
tracks:
- local_files:
  - chr*.fa.gz
  name: ref
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/
  remote_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  type: reference
- features:
  - kgID
  - mRNA
  - spID
  - spDisplayID
  - geneSymbol
  - refseq
  - protAcc
  - description
  - rfamAcc
  - name
  join:
    features:
    - PhenotypeIDs
    - OtherIDs
    track: clinvar
  local_files:
  - hg38.refSeq.chr*.gz
  name: refSeq
  nearest:
  - name
  - geneSymbol
  site:
    codon_number_feature: referenceCodonNumber
    codon_position_feature: referenceCodonPosition
    codon_sequence_feature: referenceCodon
    site_type_feature: siteType
    strand_feature: strand
  sql_statement: SELECT * FROM hg38.refGene LEFT JOIN hg38.kgXref ON hg38.kgXref.refseq
    = hg38.refGene.name
  tx_effect_feature_name: exonicAleleFunction
  type: gene
- local_files:
  - hg38.phastCons7way.wigFix.gz
  name: phastCons
  remote_dir: hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons7way/
  remote_files:
  - hg38.phastCons7way.wigFix.gz
  type: score
- local_files:
  - hg38.phyloP7way.wigFix.gz
  name: phyloP
  remote_dir: hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP7way/
  remote_files:
  - hg38.phyloP7way.wigFix.gz
  type: score
- local_files:
  - whole_genome_SNVs.tsv.chr*.bed.mapped.gz
  name: cadd
  type: cadd
- build_field_transformations:
    alleleFreqs: split [,]
    alleleNs: split [,]
    alleles: split [,]
    func: split [,]
    observed: split [\/]
  features:
  - name
  - strand
  - observed
  - class
  - func
  - alleles
  - alleleNs: int
  - alleleFreqs: float
  local_files:
  - hg38.snp146.chr*.gz
  name: dbSNP
  sql_statement: SELECT * FROM hg38.snp146
  type: sparse
- based: 1
  build_field_transformations:
    Chromosome: chr .
    OtherIDs: split [;,]
    PhenotypeIDs: split [;,]
  build_row_filters:
    Assembly: == GRCh38
  features:
  - ClinicalSignificance
  - Type
  - Origin
  - ReviewStatus
  - OtherIDs
  - ReferenceAllele
  - AlternateAllele
  - PhenotypeIDs
  local_files:
  - variant_summary.txt.gz
  name: clinvar
  required_fields_map:
    chrom: Chromosome
    chromEnd: Stop
    chromStart: Start
  type: sparse

