settings:
    analysis:
        filter: 
            autocomplete_filter:
                type: edge_ngram
                min_gram: 1
                max_gram: 20
            
        
        analyzer:
            autocomplete:
                type: custom
                tokenizer: standard
                filter:
                    - lowercase
                    - autocomplete_filter
mappings:
    _all:
        type: string
        analyzer: autocomplete
        search_analyzer: standard
    properties:
        Fragment:
            type: string
        Position:
            type: integer
        Type:
            type: string
        heterozygotes:
            type: string
        homozygotes:
            type: string
        compoundHeterozygotes:
            type: string
        minorAlleles:
            type: string
            include_in_all: false
        hg38:
            type: string
            include_in_all: false
        refSeq:
            properties:
                siteType:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                exonicAlleleFunction:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                referenceCodon:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                alleleAminoAcid:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                codonPosition:
                    type: short
                    include_in_all: false
                codonNumber:
                    type: integer
                    include_in_all: false
                strand:
                    type: string
                    include_in_all: false
                kgID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                mRNA:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                spID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                spDisplayID:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                geneSymbol:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                refseq:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                protAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                description:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                rfamAcc:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                nearest:
                    properties:
                        name:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: standard
                        geneSymbol:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: standard
                clinvar:
                    properties:
                        PhenotypeIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: standard
                        OtherIDs:
                            type: string
                            analyzer:  autocomplete
                            search_analyzer: standard
        phastCons:
            type: float
            include_in_all: false
        phyloP:
            type: float
            include_in_all: false
        cadd:
            type: float
            include_in_all: false
        dbSNP146:
            properties:
                name:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                strand:
                    type: string
                observed:
                    type: string
                    include_in_all: false
                class:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                func:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                alleles:
                    type: string
                    include_in_all: false
                alleleNs:
                    type: integer
                    include_in_all: false
                alleleFreqs:
                    type: float
                    include_in_all: false
        clinvar:
            properties:
                ClinicalSignificance:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                Type:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                Origin:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                ReviewStatus:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                OtherIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard
                ReferenceAllele:
                    type: string
                    include_in_all: false
                AlternateAllele:
                    type: string
                    include_in_all: false
                PhenotypeIDs:
                    type: string
                    analyzer:  autocomplete
                    search_analyzer: standard