# mm10
#
# special commands:
#  _asterisk    => *
#  _gene_fields => $gene_fields_str
#  _snp_fields  => $snp_fields_str
#
---
genome_name: mm10
genome_description: mouse
genome_chrs:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chrM
  - chrX
  - chrY
genome_raw_dir: /ssd/twingo/sandbox/mm10/raw
genome_index_dir: /ssd/twingo/sandbox/mm10/index

sparse_tracks:
  - type: gene
    name: knownGene
    sql_statement: SELECT _gene_fields FROM mm10.knownGene LEFT JOIN mm10.kgXref ON mm10.kgXref.kgID = mm10.knownGene.name
    features:
      - mRNA
      - spID
      - spDisplayID
      - geneSymbol
      - refseq
      - protAcc
      - description
      - rfamAcc
  - type: snp
    name: snp138
    sql_statement: SELECT _snp_fields FROM mm10.snp138
    features:
      - name
      - alleleFreqCount
      - alleles
      - alleleFreqs

genome_sized_tracks:
  - name: mm10
    type: genome
    local_dir: /ssd/twingo/sandbox/mm10/raw/seq
    local_files:
      - chr1.fa.gz
      - chr2.fa.gz
      - chr3.fa.gz
      - chr4.fa.gz
      - chr5.fa.gz
      - chr6.fa.gz
      - chr7.fa.gz
      - chr8.fa.gz
      - chr9.fa.gz
      - chr10.fa.gz
      - chr11.fa.gz
      - chr12.fa.gz
      - chr13.fa.gz
      - chr14.fa.gz
      - chr15.fa.gz
      - chr16.fa.gz
      - chr17.fa.gz
      - chr18.fa.gz
      - chr19.fa.gz
      - chrM.fa.gz
      - chrX.fa.gz
      - chrY.fa.gz
    remote_dir: hgdownload.soe.ucsc.edu/goldenPath/mm10/chromosomes/
    remote_files:
       - chr1.fa.gz
       - chr2.fa.gz
       - chr3.fa.gz
       - chr4.fa.gz
       - chr5.fa.gz
       - chr6.fa.gz
       - chr7.fa.gz
       - chr8.fa.gz
       - chr9.fa.gz
       - chr10.fa.gz
       - chr11.fa.gz
       - chr12.fa.gz
       - chr13.fa.gz
       - chr14.fa.gz
       - chr15.fa.gz
       - chr16.fa.gz
       - chr17.fa.gz
       - chr18.fa.gz
       - chr19.fa.gz
       - chrM.fa.gz
       - chrX.fa.gz
       - chrY.fa.gz
